{{- if .Values.inferenceExtension.monitoring.servicemonitor.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway-api-inference-extension.name" . }}-token
  labels:
    {{- include "gateway-api-inference-extension.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "gateway-api-inference-extension.name" . }}
type: kubernetes.io/service-account-token
{{- end }}